name: fake_firebase_security_rules
description: Fake for Firebase Security Rules. To be used by fake_cloud_firestore and mock_firebase_storage.
version: 0.5.3
repository: https://github.com/atn832/fake_firebase_security_rules
homepage: https://www.wafrat.com

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  antlr4: ^4.11.1
  cel: ^0.5.1
  equatable: ^2.0.5
  logger: ^2.0.2
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
